### ISSUE TITLE
Retrodep fails if retrieving any of the repo's fails.

### ISSUE THREAD

**Issue by mmirecki** [release-engineering/backvendor#123]
When resolving any of the repo's fails, retrodep will exit without printing any results.
I would rather expect that it will continue, printing the version of the problematic package as "?".
Some of the packages that cause an issue:
- kubevirt.io/qe-tools/pkg/ginkgo-reporters
- kubevirt.io/qe-tools/pkg/polarion-xml

https://github.com/release-engineering/retrodep/pull/122 is an interim patch that does not print the problematic packages, but at least allows retrodep to continue with the correct ones.

**Comment by twaugh** [comment]
Fixed via #119.
