### ISSUE TITLE
Support detecting release maintenance branches

### ISSUE THREAD

**Issue by DirectXMan12** [release-engineering/backvendor#17]
Some projects (e.g. Kubernetes) use maintenance branches (e.g. `release-1.9`) to track backports to stable versions in between stable releases.  It might be useful to recognize these in some capacity,

**Comment by twaugh** [comment]
The issue with doing that is that the result will not be "comparable" in the same way as a semantic pseudo-version is.

I think the Go 'modules' idea of ignoring branches altogether in pseudo-versions, and instead basing them on reachable semantic version tags and commit dates, is better.

Given the direction Go 'modules' are taking, I'm hoping projects not already using semantic version tags will move towards them.

It may make sense to put in additional effort into parsing *tags* that are not strictly semantic though.
