### ISSUE TITLE
Show dependency layers in output

### ISSUE THREAD

**Issue by jasinner** [release-engineering/backvendor#32]
It would be great if we could nest the output so that we could see easily which package was responsible for pulling in another package.

Using [grafana](https://github.com/openshift/grafana.git) as an example. In the vendor directory it has a dependency:

github.com/mattn/go-colorable

That currently shows up in the output like this:

github.com/mattn/go-colorable@167de6bfdfba052fa6b2d3664c8f5272e23c9072 =v0.0.9 ~v0.0.9

However extra analysis of he vendor directory could tell us that it's not used directly by grafana but is used as part of both:

github.com/inconshreveable/log15
github.com/fatih/color

So potentially we could nest the output to show that:

github.com/inconshreveable/log15@0decfc6c20d9ca0ad143b0e89dcaa20f810b4fb3 =v2.13 ~v2.13 / github.com/mattn/go-colorable@167de6bfdfba052fa6b2d3664c8f5272e23c9072 =v0.0.9 ~v0.0.9

github.com/fatih/color@5b77d2a35fb0ede96d138fc9a99f5c9b6aef11b4 =v1.7.0 ~v1.7.0 / github.com/mattn/go-colorable@167de6bfdfba052fa6b2d3664c8f5272e23c9072 =v0.0.9 ~v0.0.9

This would be a 'nice-to-have' feature. I wouldn't consider it a high priority as the analysis team can work out the dependency hierarchy by inspecting the source code. It might even be better suited to a unique tool, not backvendor itself.

**Comment by twaugh** [comment]
Worth noting that 'go mod graph' can already do this for projects which use Go modules.

**Comment by twaugh** [comment]
I'd rather leave this to the dependency management tools, and/or Go-with-modules support. I think backvendor is essentially a stop-gap solution until we have widespread Go modules support, which would allow us to identify the module and its dependencies used to build each executable.
