### ISSUE TITLE
Rev and Ver swapped sometimes?

### ISSUE THREAD

**Issue by jasinner** [release-engineering/backvendor#85]
I'm seeing a strange issue when running the backvendor tool on one repo:

backvendor -exclude-from=exclusions -importpath github.com/brancz/kube-rbac-proxy .
..
github.com/PuerkitoBio/purell@v1.0.1-0.20160727215603-8a290539e2e8 ~8a290539e2e8629dbc4e6bad948158f790ec31f4

Notice the Rev, and Ver seems to be swapped, it happens for all vendored dependencies, but only on this project.

**Comment by twaugh** [comment]
This is because of the glide.lock matching being reported incorrectly.
